### ISSUE TITLE
这里有一个错误 

### ISSUE THREAD

**Issue by Mantoui** [fineemb/lovelace-colorfulclouds-weather-card#1]
```
entity: weather.tao_yuan_cun
type: 'custom:weather-card'
```
​
TypeError: Failed to fetch dynamically imported module: http://10.2.0.123:8123/hacsfiles/lovelace-colorfulclouds-weather-card/weather-card-editor.js

![image](https://user-images.githubusercontent.com/4598262/92767732-f7d30800-f3c9-11ea-951e-e301dd1dec9f.png)

日志中有一个 WARNING
日志详细信息（ WARNING ）
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 2020年9月10日 下午5:49:16 (107 occurrences)
Last logged: 上午12:53:17

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for colorfulclouds doing I/O at custom_components/colorfulclouds/__init__.py, line 147: json_text = requests.get(url).content

**Comment by fineemb** [comment]
卡片等更新下一版

集成已经尝试修复, 请更新最新版后再观察一下, 谢谢

**Comment by Mantoui** [comment]
集成已经更新到最新版，卡片的这个提示依然存在
好的
