### ISSUE TITLE
weather-card-editor 这个没有上传吧

### ISSUE THREAD

**Issue by hundandadi** [fineemb/lovelace-colorfulclouds-weather-card#2]
少了weather-card-editor,不知道是依赖别的还是少传了

**Comment by plutosherry** [comment]
虽然说明：配置已经支持UI前端配置, 无需书写代码.......然而并没有这个UI配置页，应该是源码上传缺失导致的

**Comment by plutosherry** [comment]
另外是否还需要配置一下configuration.yaml 以启用colorfulclouds插件。否则前端会提示插件未启用或未安装。

**Comment by duchenpaul** [comment]
> 另外是否还需要配置一下configuration.yaml 以启用colorfulclouds插件。否则前端会提示插件未启用或未安装。

你跟我一样也在找彩云天气啊, 我看我这也用不了了

**Comment by fineemb** [comment]
新版已经完成。
