### ISSUE TITLE
日出日落时间显示错误

### ISSUE THREAD

**Issue by muxiachuixue** [fineemb/lovelace-colorfulclouds-weather-card#5]
HA版本：2021.12.8 supervised 版
是否有彩云key：是
是否安装最新彩云天气插件：是
时区是否正确：是，上海时区
GPS信息是否填写正确：是，为上海这边经纬度
其他信息是否显示正确：是

问题：
彩云卡片中日出时间显示为：“下午3:46:39”，日落时间显示为“下午11:47:20”，且第二天还是会显示错

尝试过用postman直接访问彩云API，返回信息中可以看到正确的日出日落时间，不知是否是HA版本太新，和彩云插件代码有冲突的原因？

**Comment by fineemb** [comment]
这个日出日落我并没有用彩云的，而是用的HA自带的sun.sun你查看一下对不对

**Comment by muxiachuixue** [comment]
> 这个日出日落我并没有用彩云的，而是用的HA自带的sun.sun你查看一下对不对

解决了，是HA里面系统默认的家庭位置不正确导致的，sun.sun里面的时间也是错的，解决方案如下：
在configuration.yaml文件中加入如下代码
`homeassistant:
   name: YOUR_HOME_NAME
   time_zone: Asia/Shanghai
   latitude: YOUR_HOME_LATITUDE
   longitude: YOUR_HOME_LONGITUDE`
其中`YOUR_HOME_NAME`是你家庭名称，可随意命名；`YOUR_HOME_LATITUDE`和`YOUR_HOME_LONGITUDE`分别为家庭GPS经纬度坐标（注意，非高德坐标）
保存后重启HA即可恢复正常
